telus/tds-core

- src/components/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
- src/components/ExpandCollapse/ExpandCollapse.jsx
- src/components/ExpandCollapse/Panels.jsx
- src/components/ExpandCollapse/__tests__/ExpandCollapse.spec.jsx
- src/components/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
Allows developers to use common react patterns (ternary operators or the use of &&) to conditionally render panels inside the expand-collapse component
Closes #444
Uses the children API (https://reactjs.org/docs/react-api.html#reactchildren) to convert the children prop into a flat array and filter out the falsy values (null, false or undefined)
This required updating the snapshot as per the docs.
> feat(expand-collapse): Enable conditional rendering of panels

- src/components/ExpandCollapse/Accordion/Accordion.jsx
- src/components/ExpandCollapse/ExpandCollapse.jsx
- src/components/ExpandCollapse/PanelWrapper/PanelWrapper.jsx
- src/components/Tooltip/Tooltip.jsx
- src/old-components/SelectorCounter/SelectorCounter.jsx
- src/old-components/Spinner/Spinner.jsx
Property initializers are detailed in the proposal "ES Class Fields & Static Properties." While an experimental feature that has yet to be ratified, this feature works so well with React that the Facebook team has written about using it internally. Using them will lead to simpler and cleaner code. Please check the following link for further details: https://www.fullstackreact.com/articles/use-property-initializers-for-cleaner-react-components/
Note: this is a re-opening of https://github.com/telusdigital/tds/pull/454
> refactor: use class properties transform

- src/components/Select/Select.modules.scss
- Link to related issues: 
- #267  
- [TDS-251](https://telusdigital.atlassian.net/browse/TDS-251)
- [ x ] Explanation of how existing TDS code falls short
Select component dropdown caret is not clickable
- [ x ] Alignment to approved Sketch file and creative mockups
- [ x ] Documentation is finalized
- [ x ] Code meets AA accessibility guidelines
- [ x ] Code passes automated tests and style checks
- [ x ] New code is unit tested where appropriate (developer should use own judgement)
> TDS 251 - Make caret in Select component visible and clickable

- package.json
Don't need main, module, and files anymore in the base package.json.
> chore(package.json): Remove un-needed fields

- config/eslint.config.js
- docs/components/MarkdownHeading/__tests__/MarkdownHeading.spec.jsx
- docs/components/SectionHeading/__tests__/SectionHeading.spec.jsx
- package.json
- packages/DimpleDivider/__tests__/DimpleDivider.spec.jsx
- tech-snacks.md
- yarn.lock
Tech snack!
* upgrade eslint-plugin-jest version to fix peer dependency warning
* extend from @telusdigital/eslint-config with recommended syntax
* extend from prettier with recommended syntax for config + plugin
> chore(eslint): Upgrade eslint configs and prettier integration

- packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
- packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
- packages/StandaloneIcon/__tests__/__snapshots__/StandaloneIcon.spec.jsx.snap
- packages/Tooltip/__tests__/__snapshots__/Tooltip.spec.jsx.snap
- shared/components/Clickable/Clickable.jsx
- shared/components/Clickable/__tests__/__snapshots__/Clickable.spec.jsx.snap
Apply patch from #493 to the latest codebase.
- Change default button behaviour of the Clickable component to `type="button"`
> fix(clickable): change default type to button

- config/styleguide.config.js
- docs/components/Editor/Editor.js
- docs/components/Markdown/Markdown.js
- docs/components/Pathline/PathlineRenderer.js
- docs/components/StyleGuide/StyleGuideRenderer.jsx
- docs/components/TabButton/TabButtonRenderer.js
- docs/css/codemirror/ttcn.css
- docs/css/highlight_js/docco.css
- docs/dev-index.html
- docs/index.html
- packages/Card/Card.md
- packages/SelectorCounter/SelectorCounter.md
- packages/TextArea/TextArea.md
We are now loading our own custom AAA colour accessible themes that came from:
- `node_modules/codemirror/theme/ttcn.css`
- `node_modules/highlight.js/styles/docco.css`
Note: As part of this story we found out that the accessible green on athens grey background is not AAA colour accessible with small fonts, so I update the Card colour variants example to not have the green chevron link on grey background Card.
You can now run `yarn dev` and then `yarn test:accessibility` in another tab to see that all 26 nightwatch accessibility assertions pass.
> TDS-528 - Fix accessibility issues in Styleguidist

- guide/contributing/codebase-overview.md
- guide/getting-started/developers.md
- guide/roadmap.md
- Updated roadmap
- Includes Release 2, post-lerna setup
- moved old releases to a new 'history' heading at the bottom
- Changed scaffold example a bit
- Updated developer example to match our [Card example](https://tds.telus.com/components/index.html#card)
> docs(roadmap): add release 2

- shared/components/Choice/Choice.modules.scss
#462 - Fixed a small alignment issue with the buttons and their labels. The radio buttons have been moved up by 1px.
**Before**
**After**
> fix(choice): fix radio button label alignment issue

- config/rollup.config.js
- packages/Input/Input.jsx
- packages/Select/Select.jsx
- packages/TextArea/TextArea.jsx
- shared/components/FormField/FormField.jsx
- shared/components/FormField/FormField.md
Please rebase and merge
- fix rollup config so that `componentWithName` gets bundled properly for Select, TextArea, FormField, and Input components
Tested in starter kit.
> fix(build): resolve proptypes array

- packages/ButtonLink/ButtonLink.modules.scss
- packages/Link/Link.modules.scss
- shared/styles/Links.modules.scss
Will also be applying the same styling to `Link` to ensure consistency in another PR.
Tested on Chrome, Firefox, Safari, IE Edge, IE 11.
> fix(core-button-link): standardize focus outline across browsers #445 [Rebase and Merge me!] 

- packages/FlexGrid/Col/Col.jsx
- packages/FlexGrid/Col/Col.modules.scss
- packages/FlexGrid/FlexGrid.jsx
- packages/FlexGrid/FlexGrid.modules.scss
- packages/FlexGrid/Row/Row.jsx
- packages/FlexGrid/Row/Row.modules.scss
- packages/FlexGrid/Row/__tests__/__snapshots__/Row.spec.jsx.snap
- packages/FlexGrid/__tests__/FlexGrid.spec.jsx
- packages/FlexGrid/__tests__/__snapshots__/FlexGrid.spec.jsx.snap
This pull request addresses issue #518 and also deprecates the `centre` prop. This was done because the fixedWidth prop will also centre the grid, making `centre` redundant.
> feat(core-flex-grid): fix flexbox gutterless alignment issue and deprecate centre prop

- packages/Select/Select.jsx
- packages/Select/Select.modules.scss
- z-index interfered with neighbouring Tooltip component appearing behind the Select component
Note, removing the z-index from the Select component does not break the click-through behaviour of the downward-facing Chevron icon since `pointer-events: none` handles that on its own.
see #525
> fix(core-select): remove z-index

- packages/SelectorCounter/README.md
- packages/SelectorCounter/SelectorCounter.jsx
- packages/SelectorCounter/SelectorCounter.md
- Deprecates the SelectorCounter component
- Adds notice to documentation and README
**Please rebase and merge** and:
- deprecate this component when publishing to npm
- add deprecation notice to changelog and release notes
> feat(core-selector-counter): deprecate component

- package.json
- scripts/build.js
- scripts/e2e.js
- scripts/publish.js
- scripts/utils/arrayToGlob.js
- scripts/utils/getUpdatedPackageNames.js
also accept component names on the command line for `yarn build`, `yarn test:e2e`, and `yarn lerna:publish` scripts
examples:
```
yarn publish     # Starts publishing by detecting changed packages with `lerna updated`
yarn publish @tds/core-component     # Starts publishing only @tds/core-component
```
> feat(build): introduce a publish.js script to scope by packages

- package.json
- scripts/publish.js
- scripts/utils/getUpdatedPackageNames.js
- scripts/utils/parseArgs.js
solves for out of order releasing to allow for things like: `yarn lerna:publish @tds/core-select
--since @tds/core-select@1.0.2`
* Adds the `minimist` package to do command line argument parsing
> feat(build): support lerna options in the publish.js script

- package.json
- scripts/prePr.js
- yarn.lock
...by using the lerna publish command directly
Ok, using a new strategy here by calling a lerna command directly. It uses a non-public interface though, so may be a bit brittle, but I think its likely the most straightforward solution.
Now the output will look like this:
```
yarn run v1.5.1
$ node scripts/prePr.js --conventional-commits --yes
lerna info versioning independent
lerna info ignore [ '*.md', '*.spec.jsx', '*.snap' ]
lerna info Checking for updated packages...
lerna info Comparing with lerna-reset-3.
lerna info Checking for prereleased packages...
Changes:
- @tds/core-flex-grid: 1.1.0 => 1.2.0
- @tds/core-notification: 1.0.2 => 1.1.0
lerna info auto-confirmed
🤔 If this is not what you expected, ensure that your commit messages follow the Conventional Commits specification: …
```
> chore(build): improve the prepr script

- README.md
- guide/README.md
- guide/SUMMARY.md
- guide/contact.md
- guide/contributing/codebase-overview.md
- guide/contributing/contributing.md
- guide/contributing/developer-guide.md
- guide/getting-started/designers.md
- openshift/openshift-template.yml
- package.json
- packages/Responsive/Responsive.md
- scripts/scaffolding/package.json
Immediately after merging this PR, the repo name must be changed using the Github UI. https://github.com/telusdigital/tds/settings
I've left all the package.json and changelogs out, Github will set up a redirect so I don't think its worth it to make such a large change and mess with lerna.
> chore(docs): rename repo links to tds-core

- docs/components/overrides/StyleGuide/StyleGuideRenderer.js
- docs/scss/styleguide.scss
- packages/FlexGrid/Col/Col.md
- packages/FlexGrid/FlexGrid.md
- packages/FlexGrid/Row/Row.md
- packages/Notification/Notification.md
This is a WIP. What do you all think?
Adding the `docs_full-width-playground` class to component playgrounds will cause it to "break out" of it's parent container and display the component using the full browser width. This will allow us to better showcase full width components such as `Notification` or `FlexGrid`.
It is not active when the sidebar is being shown:
And it is active when the sidebar is hidden:
I briefly attempted other strategies, but this one seemed to be the most straightforward one, even though it does involve some fancy/potentially brittle CSS.
> chore(docs): full width component playgrounds

- shared/components/FormField/FormField.jsx
...fixes a race condition when consumers modify the input, such as formatting.
Re: #606 
This fixes an issue brought up by @ah-arch when applying formatting to input fields, specifically when preventing certain characters from being typed. A sample test case of this that will work within styleguidist is:
```jsx
initialState = {
value: ''
}
const numbersOnly = event => {
const noAlpha = event.target.value.replace(/[a-z]/g, "");  
setState({ value: noAlpha })
}
<Input
label="Phone number"
value={state.value}
onChange={numbersOnly}
/>
```
Before this PR, you would briefly see the letters as the user typed. I believe this was due to our use of `setState`  followed by the call to `onChange`. Because `setState` is actually an asynchronous function, its not guaranteed to be called before …
> fix(shared-form-field): call onchange after async setstate

- commitlint.config.js
In an effort to clean up the commitlint, I've added all our top level folders as commit lint scopes. So we could follow these standards:
* If touching a component/package, use that as the scope: `feat(core-button): ...` or `chore(shared-animations): ...`
* If not, use the most directly affected folder: `test(e2e): ...`
* Use "dependencies" when adding/removing/updating dependencies: `chore(dependencies): ...`
* Many of the files in the root are configuration files that would also use the "config" scope, such as ".babelrc" or "commitlint.config.js"
* If nothing else fits, use "other": `chore(other): ...`
I think this should cover all use cases, and we shouldn't need to modify the scopes unless we change folder structure.
> chore(config): add all folders to commitlint scopes

- .github/ISSUE_TEMPLATE/defect_template.md
- .github/ISSUE_TEMPLATE/feature_template.md
- add front matter to issue templates so that GitHub can detect them as official issue templates and leverage the new issue opening experience: https://help.github.com/articles/creating-issue-templates-for-your-repository/
> chore(github): add front matter to issue templates

- packages/Checkbox/Checkbox.md
- packages/Radio/Radio.md
- shared/components/Choice/Choice.jsx
- Addresses the Checkbox and Radio state issue described in: https://github.com/telusdigital/tds-core/issues/641
- _When using application state to set the checked prop of Checkbox, the state of the Checkbox gets out of sync with the state of the application, causing the Checkbox to display the wrong state._
- This is first seen on _Input_, _Select_, _Textarea_ in issue: https://github.com/telusdigital/tds-core/issues/606
- Fixes the issue by:
- duplicating the solution in this PR: https://github.com/telusdigital/tds-core/pull/590
- correcting sample code in both Checkbox and Radio, which used to reflect the expected but incorrect state
----
```
[Components Spec] Test Suite
================================
Running:  @tds/core-checkbox
✔ Element <#checkbox> was visible after 30 …
```
> fix(shared-choice): call onchange after async setstate

- packages/InputFeedback/InputFeedback.jsx
- packages/InputFeedback/__tests__/InputFeedback.spec.jsx
Adds `role="alert"` to all input errors by default. Addresses #654.
prepr:
```
Changes:
- @tds/core-checkbox: 1.0.4 => 1.0.5
- @tds/core-input: 1.0.6 => 1.0.7
- @tds/core-input-feedback: 1.0.1 => 1.0.2
- @tds/core-radio: 1.0.4 => 1.0.5
- @tds/core-select: 1.0.7 => 1.0.8
- @tds/core-text-area: 1.0.6 => 1.0.7
- @tds/core-tooltip: 1.0.4 => 1.1.0
- @tds/shared-choice: 1.0.4 => 1.0.5 (private)
- @tds/shared-form-field: 1.0.5 => 1.0.6 (private)
```
This can be rebased.
> fix(core-input-feedback): add role alert to error message

- packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
- packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx
- packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
- shared/components/Animation/Reveal.jsx
- shared/components/Animation/__tests__/__snapshots__/Reveal.spec.jsx.snap
Allows ExpandCollapse to adapt to the size of its children. Addresses #671.
prepr:
```
Changes:
- @tds/core-expand-collapse: 1.0.3 => 1.0.4
- @tds/core-input: 1.0.6 => 1.0.7
- @tds/core-select: 1.0.7 => 1.0.8
- @tds/core-text-area: 1.0.6 => 1.0.7
- @tds/core-tooltip: 1.0.4 => 1.1.0
- @tds/shared-animation: 1.0.1 => 1.0.2 (private)
```
This can be rebased.
> fix(core-expand-collapse): enable adaptive panel size

- package.json
- packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap
This will build all components on our prepush hook. While slower, this will prevent screenshot issues due to unbuilt components.
> chore(scripts): add build all on git push

- package.json
- packages/Checkbox/Checkbox.jsx
- packages/Checkbox/__tests__/Checkbox.spec.jsx
- packages/Checkbox/__tests__/__snapshots__/Checkbox.spec.jsx.snap
- packages/Radio/Radio.jsx
- packages/Radio/__tests__/Radio.spec.jsx
- packages/Radio/__tests__/__snapshots__/Radio.spec.jsx.snap
- packages/Tooltip/Tooltip.jsx
- packages/Tooltip/package.json
- shared/components/Choice/Choice.jsx
- shared/components/Choice/package.json
- shared/components/FormField/FormField.jsx
- shared/components/FormField/package.json
- shared/utils/generateId/__tests__/generateId.spec.js
- shared/utils/generateId/generateId.js
- shared/utils/generateId/package.json
See #682 
Update Radio and Checkbox to allow numbers to be passed as value.
```
Changes:
- @tds/core-checkbox: 1.0.5 => 1.0.6
- @tds/core-expand-collapse: 1.1.1 => 1.1.2
- @tds/core-input: 1.0.8 => 1.0.9
- @tds/core-radio: 1.0.5 => 1.0.6
- @tds/core-select: 1.0.9 => 1.0.10
- @tds/core-text-area: 1.0.8 => 1.0.9
- @tds/core-tooltip: 2.0.1 => 2.0.2
- @tds/shared-choice: 1.0.5 => 1.0.6 (private)
- @tds/shared-form-field: 1.0.6 => 1.0.7 (private)
- @tds/util-generate-id: 1.0.0-dev => 1.0.0 (private)
```
> refactor(util-generate-id): move into private package

- packages/Button/__tests__/__snapshots__/Button.spec.jsx.snap
- packages/ButtonLink/__tests__/__snapshots__/ButtonLink.spec.jsx.snap
- shared/components/BaseButton/BaseButton.jsx
- shared/components/BaseButton/BaseButton.modules.scss
See #662 
Remove the `<FlexBox>` component from `<BaseButton>`, `<BaseButton>` should just render `children`.
```
Changes:
- @tds/core-button: 1.1.0 => 1.1.1
- @tds/core-button-link: 1.1.0 => 1.1.1
- @tds/shared-base-button: 1.2.0 => 1.2.1 (private)
```
> refactor(shared-base-button): remove flexbox

- packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap
- packages/Paragraph/Paragraph.jsx
- packages/Paragraph/Paragraph.modules.scss
- packages/Paragraph/__tests__/__snapshots__/Paragraph.spec.jsx.snap
See #643 
Prevent text from overflowing its parents in IE11.
```
Changes:
- @tds/core-checkbox: 1.1.0 => 1.1.1 (PATCH)
- @tds/core-input: 1.0.10 => 1.0.11 (PATCH)
- @tds/core-notification: 1.1.7 => 1.1.8 (PATCH)
- @tds/core-paragraph: 1.0.2 => 1.0.3 (PATCH)
- @tds/core-radio: 1.1.0 => 1.1.1 (PATCH)
- @tds/core-select: 1.0.11 => 1.0.12 (PATCH)
- @tds/core-text-area: 1.0.9 => 1.0.10 (PATCH)
- @tds/shared-choice: 1.0.6 => 1.0.7 (private) (PATCH)
- @tds/shared-form-field: 1.0.7 => 1.0.8 (private) (PATCH)
```
> fix(core-paragraph): prevent overflow on ie11

- packages/FlexGrid/FlexGrid.modules.scss
- packages/FlexGrid/Row/Row.modules.scss
Load order of css can be incorrect in cases overwriting the reverse classes and preventing users from being able to reverse grid elements.
```
Changes:
- @tds/core-checkbox: 1.1.0 => 1.1.1
- @tds/core-flex-grid: 2.1.0 => 2.1.1
- @tds/core-input: 1.0.10 => 1.0.11
- @tds/core-notification: 1.1.7 => 1.1.8
- @tds/core-paragraph: 1.0.2 => 1.0.3
- @tds/core-radio: 1.1.0 => 1.1.1
- @tds/core-select: 1.0.11 => 1.0.12
- @tds/core-text-area: 1.0.9 => 1.0.10
- @tds/shared-choice: 1.0.6 => 1.0.7 (private)
- @tds/shared-form-field: 1.0.7 => 1.0.8 (private)
```
> fix(core-flex-grid): add specificity to styles

- packages/FlexGrid/Col/Col.jsx
- packages/FlexGrid/Col/Col.md
- packages/FlexGrid/Col/Col.modules.scss
- packages/FlexGrid/Col/__tests__/Col.spec.jsx
- packages/FlexGrid/Col/__tests__/__snapshots__/Col.spec.jsx.snap
- packages/FlexGrid/FlexGrid.jsx
- packages/FlexGrid/Row/Row.jsx
- packages/FlexGrid/__tests__/__snapshots__/FlexGrid.spec.jsx.snap
- packages/FlexGrid/calculateLevel.js
- packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap
See #707
Add hide props to `<FlexGrid.Col />`
```
Changes:
- @tds/core-checkbox: 1.1.0 => 1.1.1
- @tds/core-flex-grid: 2.1.0 => 2.2.0
- @tds/core-input: 1.0.10 => 1.0.11
- @tds/core-notification: 1.1.7 => 1.1.8
- @tds/core-paragraph: 1.0.2 => 1.0.3
- @tds/core-radio: 1.1.0 => 1.1.1
- @tds/core-select: 1.0.11 => 1.0.12
- @tds/core-text-area: 1.0.9 => 1.0.10
- @tds/shared-choice: 1.0.6 => 1.0.7 (private)
- @tds/shared-form-field: 1.0.7 => 1.0.8 (private)
```
> Feature col hidden props

- packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
- packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx
- packages/ExpandCollapse/PanelWrapper/PanelWrapper.modules.scss
- packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
See #655 
```
Changes:
- @tds/core-expand-collapse: 1.1.1 => 1.1.2
```
~~* [ ] New code is unit tested~~
> fix(core-expand-collapse): fix header overflow on tertiary text for IE11

- guide/contributing/developer-guide.md
This pull requests adds a section to the developer contributor guide. This section explains what our tests are, how to run them manually, and which options are available when running manually.
```
Changes:
- @tds/core-notification: 1.1.9 => 1.2.0
```
> docs(guide): add section to developer guide on tests

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/defect_template.md
- .github/ISSUE_TEMPLATE/feature_template.md
- .github/PULL_REQUEST_TEMPLATE.md
None
Add warnings regarding posting links to staging.
After merging, replicate these changes in tds-community.
> docs(github): add warning for posting links to staging

- guide/README.md
Quick addition to the TDS front page to make some of our key documentation more visible.
> docs(guide): add quick links to TDS front page

- packages/ChevronLink/ChevronLink.modules.scss
[ChevronLink] Overflow on IE11 #642
#TDS Issue #642 
* Setting max-width:100% on ```.link``` on  ChevronLink.modules.scss
> fix(core-chevron-link): ie11 overlfow issue

- package.json
None
Run lerna clean before linting, that way errors related to scanning `node_modules` go away. Yay or nay?
This is related to an issue where dependency version mismatching can cause `node_modules` folders to appear in package directories, causing eslint errors to appear. `lerna clean` deletes all unnecessary `node_modules` directories, allowing linters to run purely on our code. This appear more frequently in tds-community.
If approved, please replicate in tds-community.
> chore(config): run lerna clean before linting

- package.json
This updates our git hooks in `package.json` to use the new format required by Husky.
prepr:
```
Changes:
- @tds/core-notification: 1.1.9 => 1.2.0
```
> chore(config): update husky hooks

- packages/Box/__tests__/Box.spec.jsx
- packages/ButtonLink/__tests__/ButtonLink.spec.jsx
- packages/ChevronLink/__tests__/ChevronLink.spec.jsx
- packages/DimpleDivider/__tests__/DimpleDivider.spec.jsx
- packages/DisplayHeading/DisplayHeadingSup/__tests__/HeadingSup.spec.jsx
- packages/DisplayHeading/__tests__/DisplayHeading.spec.jsx
- packages/ExpandCollapse/__tests__/ExpandCollapse.spec.jsx
- packages/HairlineDivider/__tests__/HairlineDivider.spec.jsx
- packages/Heading/HeadingSup/__tests__/HeadingSup.spec.jsx
- packages/Heading/__tests__/Heading.spec.jsx
- packages/Link/__tests__/Link.spec.jsx
- packages/Paragraph/__tests__/Paragraph.spec.jsx
- packages/Small/__tests__/Small.spec.jsx
- packages/StandaloneIcon/__tests__/StandaloneIcon.spec.jsx
- packages/Strong/__tests__/Strong.spec.jsx
- packages/Text/TextSup/__tests__/TextSup.spec.jsx
- packages/Text/__tests__/Text.spec.jsx
- packages/WaveDivider/__tests__/WaveDivider.spec.jsx
- shared/components/Icon/__tests__/Icon.spec.jsx
This changes all of our Jest tests over from toHaveTagName to toHaveDisplay name, as the former no longer works in newer versions of our testing suite.
> Change tests from toHaveTagName to toHaveDisplayName

- guide/contributing/developer-guide.md
Copies over the commit type chart from community for some parity between docs.
> docs(guide): add commit type chart to dev guide

- scripts/publish.js
- scripts/utils/getPackageNames.js
This disables lerna's selective publishing arguments. This functionality is broken, and is no longer part of our process. The publish docs have been updated in accordance with this.
> chore(scripts): disable lerna selective publish

- packages/Checkbox/package.json
- packages/ExpandCollapse/package.json
- packages/Input/package.json
- packages/Tooltip/Tooltip.jsx
- packages/Tooltip/__tests__/Tooltip.spec.jsx
- packages/Tooltip/__tests__/__snapshots__/Tooltip.spec.jsx.snap
- packages/Tooltip/package.json
- shared/utils/generateId/generateId.js
- shared/utils/generateId/package.json
- yarn.lock
This fixes an issue where multiple tooltips that are not attached to an input could be opened at the same time. Additionally, it removes the `core-js` dependency and replaces it with the simpler `array-find-es6` dependency, which reduces our build size by around 600 lines.
> fix(core-tooltip): prevent multiple tooltips from being open on one page

- shared/components/FormField/FeedbackIcon.jsx
See #861 
Do not default to rendering an error icon if `feedback !== 'success'`
> fix(shared-form-field): conditionally render icons

- packages/ExpandCollapse/ExpandCollapse.jsx
- packages/ExpandCollapse/__tests__/ExpandCollapse.spec.jsx
#879
- the code makes your that the ExpandCollapse component does not re-render
> fix(core-expand-collapse): fixing expand collapse defect with Checkbox

- package.json
- scripts/commit-scope-lint.js
- yarn.lock
This PR makes the process of committing faster by including a new `test:quick` option.  Additionally, it will now lint commits to make sure that the files included in it are using the correct scope.
> Improve husky hooks

- config/nightwatch.conf.js
- docker-compose.yml
- e2e/globals.js
- scripts/docker-e2e.sh
- scripts/utils/parseArgs.js
This fixes some issues with the new e2e implementation.
- The test will now once again test only packages that were updated by default.
- The "cannot write to chromelog" error will no longer appear at the end of tests.
- The e2e startup message has been modified to indicate that no action is required from the user for it to start.
> Docker e2e fixes

- scripts/commit-scope-lint.js
This PR fixes an issue where a scope error will occur if a contributor update takes place by adding an `excludedFiles` array.
> chore(scripts): protect contributor updates from scope error

- guide/design/motion.md
- Updated the `beta` tag in the title to "(beta)" instead of using superscript, because Gitbook handles superscripts differently.
> chore(guide): update motion guide title

- package-lock.json
- packages/FlexGrid/package.json
Because we are refactoring this soon, downgrading to a version that used the old API seems like an ok idea. This way there at least won't be warnings anymore while we wait to refactor.
> fix(core-flex-grid): downgrade react-broadcast

- guide/SUMMARY.md
- guide/design/heuristics.md
- guide/design/principles.md
On the request of #888, this adds docs to our front-facing page about usability heuristics. It also links to it in the design principles page.
> docs(guide): add usability heuristics doc

- packages/colours/index.cjs.js
* `index.cjs.js` now actually exports the colours object.
> fix(core-colours): use module.exports instead of exports

- packages/Video/ControlBar/ControlBar.jsx
- packages/Video/Video.jsx
- packages/Video/__tests__/__snapshots__/Video.spec.jsx.snap
- packages/WebVideo/WebVideo.md
This PR fixes mobile detection on `Video` when it is rendered using server-side rendering. Additionally, it corrects the `posterSrc` prop verification.
> fix(core-video): improve mobile detection for server-side rendering

- packages/Input/package.json
- packages/Select/package.json
Remove `react-transition-group`
`react-transition-group` is a `devDependency` of both `core-input` and `core-select` but is never used.
> Fix @tds/core-input, @tds/core-select

- packages/WaveDivider/WaveDivider.jsx
- Replaces `includes` with `indexOf` to support IE11
> fix(core-wave-divider): fix for ie11 compatibility issues

- guide/roadmap.md
Updated roadmap, TDSv3 section, link to sunset strategy and removed history section
> docs(guide): update roadmap and remove history

- babel.config.js
- config/rollup.config.js
- package-lock.json
- package.json
- packages/UnorderedList/UnorderedItem/UnorderedItem.jsx
- packages/WebVideo/WebVideo.jsx
This is a fix that adds `@babel/plugin-proposal-object-rest-spread` to our babel config, allowing advanced usage of the spread operator in IE 11. For instance, conditional spreading:
`...(isEnabled ? {color: 'hotpink'})`
One thing to note is that in order for this to avoid the compatibility issues in IE 11, the `loose` option for the plugin has been enabled. (See: https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread#loose)
What does that mean? Well in most cases, not much. This should not affect most uses of the spread operator. However, it is slightly different from where we had it before. This option causes all spread operators to behave like `Object.assign()`s using babel's `extends` helper. In short, this means two things:
1. Objects with defined setters will have those …
> chore(other): add babel plugin for conditional object spreading in IE 11

- packages/OrderedList/OrderedItem/OrderedItem.jsx
- packages/OrderedList/OrderedItem/OrderedItem.modules.scss
- packages/OrderedList/__tests__/__snapshots__/OrderedList.spec.jsx.snap
- packages/OrderedList/package.json
This fixes a rendering issue in Firefox where a blank line will appear above an `OrderedList` if an item contains a `Paragraph` component.
Merge this before the Styled Components version of `OrderedList`!
> fix(core-ordered-list): use typography styles directly

- guide/v3-upgrade.md
This adds some migration info for those coming from CSS Modules to styled-components. Additionally, it shouts out Global Elements endpoint V2.
> docs(guide): add scss to styled-components in migration guide

- config/rollup.config.js
- package-lock.json
- packages/ExpandCollapse/Accordion/Accordion.jsx
- packages/ExpandCollapse/ExpandCollapse.jsx
- packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx
- packages/ExpandCollapse/Panels.jsx
- packages/ExpandCollapse/package.json
- packages/prop-types/componentWithName.js
This PR dramatically reduces the diff size of ExpandCollapse by replacing `airbnb-prop-types` with our own. `core-js` has also been removed as a dependency, opting to use `Array.from` and having Babel handle the IE 11 compatibility.
There is also a fix for `util-prop-types` that prevents errors on conditional rendering.
Example : `{false && <ExpandCollapse.Panel>stuff</ExpandCollapse.Panel>}`
> Reduce ExpandCollapse dist size & prevent prop error on conditional rendering

- packages/Button/Button.jsx
- packages/Button/__tests__/__snapshots__/Button.spec.jsx.snap
See #794 
for iOS <= 10, by setting the `<button>` element to `inline-flex` breaks the calculation of the width of the text inside the `<button>` and hence any texts inside the button will not be centerred.
To fix this issue while not breaking IE 11, the best method so far is to wrap the text with a `<span>` element and set it to width:100%. This 'hack' seems to work for iOS <= 10 and did not break any other browser such as IE 11.
- Created a `<ButtonTextWrapper>` styled component to wrap button text to ensure it has a width of 100% for cross browser compatibility; this `<ButtonTextWrapper>` is exported and can be used by other components if needed.
> fix(core-button): adding a span inside basic button to center text

- packages/Input/Input.jsx
- packages/Input/__tests__/Input.spec.jsx
See #1123 
Do not include `value` prop if using an uncontrolled `Input`.
> fix(core-input): remove value from props when input is uncontrolled

- packages/StandaloneIcon/StandaloneIcon.jsx
- packages/StandaloneIcon/__tests__/StandaloneIcon.spec.jsx
- packages/StandaloneIcon/__tests__/__snapshots__/StandaloneIcon.spec.jsx.snap
- packages/StandaloneIcon/package.json
- packages/Tooltip/__tests__/__snapshots__/Tooltip.spec.jsx.snap
See #985 
Render a11yText in an A11yContent component instead of as an aria-label on the button which causes accessbility errors when run through WAVE
> [StandaloneIcon] - render a11yText in A11yContent 

- packages/Input/__tests__/__snapshots__/Input.spec.jsx.snap
- packages/Select/__tests__/__snapshots__/Select.spec.jsx.snap
- packages/StandaloneIcon/StandaloneIcon.jsx
- packages/StandaloneIcon/__tests__/StandaloneIcon.spec.jsx
- packages/StandaloneIcon/__tests__/__snapshots__/StandaloneIcon.spec.jsx.snap
- packages/TextArea/__tests__/__snapshots__/TextArea.spec.jsx.snap
- packages/Tooltip/__tests__/__snapshots__/Tooltip.spec.jsx.snap
This removes the `aria-label` attribute in StandaloneIcon so it will pase WAVE tests.
> fix(core-standalone-icon): remove aria-label attribute

- package.json
This will change all of our main bootstrap scripts to use `npm ci` over `npm install` to avoid changing the package-lock.json. I have added a `bootstrap:slow` option that will bootstrap using `npm install`. This will mostly be used for troubleshooting or local repo repair if there's something wrong with the lock file.
> chore(other): change main bootstrap scripts to npm ci, add slow opt

- packages/Radio/Radio.jsx
- packages/Radio/__tests__/__snapshots__/Radio.spec.jsx.snap
When the label text is long, it does not wrap in IE.
Issue occurs below in IE when the label text is longer than the bounding box.
> fix(core-radio): wrap long labels in ie

- packages/Tooltip/Tooltip.jsx
- packages/Tooltip/__tests__/__snapshots__/Tooltip.spec.jsx.snap
See #1187 
- Added `type="button"` on the `StandaloneIcon` in `Tooltip`
```
Changes:
- @tds/core-tooltip: 4.0.2 => 4.0.3
```
> fix(core-tooltip): add button type for tooltip button

- guide/contributing/codebase-overview.md
- guide/getting-started/developers.md
- guide/v3-upgrade.md
Removes references to using CSS and replaces them with styled-components references. Also brings the terminology of some parts of the docs more up to date, and adds Nightwatch under our used tools.
> docs(guide): update guide pages for styled-components, minor cleanup

- packages/Input/Input.jsx
- packages/Input/__tests__/Input.spec.jsx
This PR adds event to `rest.onKeyDown(e)` in Input Component.
> fix(core-input): add event propagation to onKeyDown to Input

- packages/Card/Card.jsx
- packages/Card/__tests__/__snapshots__/Card.spec.jsx.snap
- packages/TermsAndConditions/Footnote/Footnote.jsx
- packages/TermsAndConditions/Footnote/__tests__/__snapshots__/Footnote.spec.jsx.snap
The shadow value in TDS Card right now uses a grey opacity, this does not work well in instances where it overlaps an image. This PR replaces this shadow with black opacity.
> [fix/card] - replace box-shadow in Card and Footnote

- packages/Spinner/Spinner.jsx
- packages/Spinner/__tests__/__snapshots__/Spinner.spec.jsx.snap
- packages/Spinner/package.json
Fixes the resizing of the child component when inline='true' and a mobile view port
> fix(core-spinner): use full width given a medium and lower view

- .all-contributorsrc
- README.md
- circle.yml
- packages/FlexGrid/FlexGrid.jsx
- packages/FlexGrid/FlexGrid.md
- packages/FlexGrid/__tests__/__snapshots__/FlexGrid.spec.jsx.snap
- packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap
- packages/StepTracker/__tests__/__snapshots__/StepTracker.spec.jsx.snap
- packages/TermsAndConditions/Footnote/__tests__/__snapshots__/Footnote.spec.jsx.snap
- packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap
In order to facilitate accessible layouts, particularly when customers change their browser font size, the FlexGrid should adapt to changes in the body’s font size.
> fix/flexgrid-rem: convert px units to rem in flexgrid container

- packages/Breadcrumbs/Breadcrumbs.jsx
- packages/Breadcrumbs/Item/Item.jsx
- packages/Breadcrumbs/__tests__/Breadcrumbs.spec.jsx
- packages/Breadcrumbs/__tests__/__snapshots__/Breadcrumbs.spec.jsx.snap
- packages/ChevronLink/ChevronLink.jsx
- packages/ChevronLink/__tests__/ChevronLink.spec.jsx
- packages/InteractiveIcon/InteractiveIcon.jsx
- packages/InteractiveIcon/__tests__/InteractiveIcon.spec.jsx
- packages/InteractiveIcon/__tests__/__snapshots__/InteractiveIcon.spec.jsx.snap
- packages/InteractiveIcon/svgs/Add.jsx
- packages/InteractiveIcon/svgs/Close.jsx
- packages/InteractiveIcon/svgs/PlayVideo.jsx
- packages/InteractiveIcon/svgs/Subtract.jsx
- packages/Link/Link.jsx
- packages/Link/__tests__/Link.spec.jsx
- packages/Link/__tests__/__snapshots__/Link.spec.jsx.snap
- packages/Link/package.json
- packages/TermsAndConditions/TermsAndConditions.jsx
- packages/TermsAndConditions/__tests__/TermsAndConditions.spec.jsx
- packages/Tooltip/Tooltip.jsx
- packages/Tooltip/__tests__/Tooltip.spec.jsx
- packages/Tooltip/__tests__/__snapshots__/Tooltip.spec.jsx.snap
- packages/Tooltip/package.json
- packages/hocs/index.js
- packages/hocs/withForwardedRef.jsx
All focusable elements should utilize React’s `forwardRef` feature. A minor release is made fo these components:
- Terms and Conditions:
> Add forwardRef to interactive components

- packages/colours/package.json
Fixes #1278 
There were some issues when trying to run `@tds/core-colours` postinstall script using MINGW64 on Windows.
Before:
After:
> fix(core-colours): fix path to deprecate.js for windows

- .all-contributorsrc
- README.md
- packages/Video/MiddleControlButton/MiddleControlButton.jsx
- packages/Video/Video.jsx
This addresses an accessibility issue where the middle play/pause button would not show a focus border when selected.
> fix(core-video): add focus border to middle play/pause button

- packages/WebVideo/WebVideo.jsx
- packages/WebVideo/__tests__/__snapshots__/WebVideo.spec.jsx.snap
See #1287 
This adds an `onStart` callback to `WebVideo`. It's called `onStart` instead of `onReady` because the function gets called when play is pressed on the video splash screen, rather than when the component is loaded.
> feat(core-web-video): add onstart callback

- .all-contributorsrc
- .remarkignore
- README.md
The new version of `all-contributors-cli` required that we regenerate our config and `README.md`. Additionally, `README.md` was removed from the `.remarkignore` config, as it was causing errors.
> chore(other): re-generate contributor table

- packages/TermsAndConditions/TermsAndConditions.jsx
- packages/TermsAndConditions/__tests__/TermsAndConditions.spec.jsx
- packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap
https://github.com/telus/tds-core/issues/1320
Adds aria-expanded attribute to the button on Terms and Condition to enable screen reader announce the expanse-collapse states
> fix(core-terms-and-conditions): add aria-expanded to TermsAndConditons

- .all-contributorsrc
- README.md
- packages/Breadcrumbs/__tests__/__snapshots__/Breadcrumbs.spec.jsx.snap
- packages/Link/Link.jsx
- packages/Link/__tests__/__snapshots__/Link.spec.jsx.snap
See: #1303 
This PR changes the default prop value of `Link`'s `invert` prop to `undefined` from `false`. This prevents a prop type error where a boolean will be passed into a react-router component when used.
> Prevent react router invert prop type error

- package-lock.json
- packages/Video/ControlBar/ControlBar.jsx
- packages/Video/ControlBar/Controls/VideoButton/VideoButton.jsx
- packages/Video/ControlBar/Controls/VolumeSlider/VolumeSlider.jsx
- packages/Video/Video.jsx
- packages/Video/__tests__/__snapshots__/Video.spec.jsx.snap
- packages/WebVideo/__tests__/__snapshots__/WebVideo.spec.jsx.snap
- shared/components/VideoSplash/BigVideoButton/BigVideoButton.jsx
This PR adjusts the following:
- Adds a default focus border to the splash screen play button when focused
- Fixes a bug in `Video` where the buttons in the control bar would be focusable while the splash screen was visible
> Address Video Focus A11y Issues

- .all-contributorsrc
- README.md
- package-lock.json
- package.json
Small PR that does the following:
- Removes `Chromedriver` from our main `package.json`, as it is no longer needed.
- Removes docker install commands from bootstrap scripts. The following scripts are now available:
`bootstrap`: fully bootstraps the repo using `npm ci`
`bootstrap:install`: bootstraps the repo using `npm i`, without running the gitbook install command. (This should be used to resolve issues with or update the `package-lock.json`.
`bootstrap:legacy`: fully bootstraps the repo with the old docker command
Hopefully this makes things a little more clear when bootstrapping.
> Remove Chromedriver, New Bootstrap Commands

- packages/Link/Link.jsx
For icon, iconPosition, and forwardRefs.
forwardRefs had an `@ignore` JSDoc that wasn't taking effect on Styleguidist, until now.
> docs(core-link): add docs to props table

- .github/workflows/tds-workflow.yml
- circle.yml
- package-lock.json
- package.json
This PR changes the minimum supported version of Node on all components and the repo itself to 12. Additionally, it updates the CI actions to use Node 12.
This bumps the repo to V4.
> Upgrade TDS to Node 12

- docs/Forms.md
Adds a new section to the main form documentation on styleguidist. This goes over optional and required form fields, and provides usage guidelines.
> docs(docs): add info about optional and required form fields

- packages/InteractiveIcon/svgs/NavButton/CartEmptyBold.jsx
- packages/InteractiveIcon/svgs/NavButton/CartFilledBold.jsx
- packages/InteractiveIcon/svgs/NavButton/NotifyBold.jsx
- packages/InteractiveIcon/svgs/NavButton/ProfileBold.jsx
- packages/InteractiveIcon/svgs/NavButton/SearchBold.jsx
- packages/InteractiveIcon/svgs/NavButton/SettingsBold.jsx
- packages/InteractiveIcon/svgs/NavButton/SupportBold.jsx
- packages/InteractiveIcon/svgs/NavButton/UserAddBold.jsx
Fixes an issue where NavButtons will say that the copy prop was not provided, even though it has. The solution was to pass it to the shared NavButton component, which has the prop set as `required` just so it shows up as such in styleguidist. Additionally, this PR fixes an issue where the `variant` prop was being improperly handled in `CartFilledBold`.
> fix(core-interactive-icon): prevent props are undefined navbutton errors

- package-lock.json
- packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx
See #1372 
This prevents an issue where tertiary text will overflow onto a second line if it's too long.
> fix(core-expand-collapse): prevent tertiary text overflow

- packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
- packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx
- packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
- packages/TermsAndConditions/Footnote/Footnote.jsx
- packages/TermsAndConditions/Footnote/__tests__/__snapshots__/Footnote.spec.jsx.snap
- packages/TermsAndConditions/FootnoteLink/FootnoteLink.jsx
- packages/TermsAndConditions/TermsAndConditions.jsx
- packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap
See #1394 
- Added `type="button"` on `HeaderButtonClickable`, `StyledClickableHeading`, `StyledClickable`
> fix(core-expand-collapse,core-terms-and-conditions): add button type for clickables

- packages/FlexGrid/Col/Col.jsx
- packages/FlexGrid/Col/__tests__/__snapshots__/Col.spec.jsx.snap
- packages/FlexGrid/__tests__/__snapshots__/FlexGrid.spec.jsx.snap
- packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap
- packages/StepTracker/__tests__/__snapshots__/StepTracker.spec.jsx.snap
- packages/TermsAndConditions/Footnote/__tests__/__snapshots__/Footnote.spec.jsx.snap
- packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap
See #1373 
This prevents an issue where `HairlineDivider` will become invisible if `mdOffset` or higher is set. I've chosen to apply `flex: 1 0 auto` to all `col`s indiscriminately to reduce complexity and ensure consistency. (For example, avoiding another case of a passed down `flex` property, while also treating all `col`s the same way) This should not break any usage of `FlexGrid`, but it should be tested thoroughly in QA to be sure.
>  fix(core-flex-grid): prevent invisible hairline divider w/ mdOffset+

- packages/css-reset/fonts.js
- Add querystring hash to fonts to cache-bust fonts
> Add querystring hash to fonts

- .all-contributorsrc
- README.md
- packages/Breadcrumbs/Breadcrumbs.jsx
- packages/Breadcrumbs/Item/Item.jsx
- packages/ButtonLink/ButtonLink.jsx
- packages/ButtonLink/package.json
- packages/ChevronLink/ChevronLink.jsx
- packages/Link/Link.jsx
See #1401 
Add support for `react-router` v5 `Link` to 
- `ButtonLink`
- `Breadcrumbs`
- `Link`
- `ChevronLink`
> Add support for react-router v5 Link components

- .all-contributorsrc
- README.md
- config/jest.config.js
- scripts/build.js
- scripts/e2e.js
- scripts/publish.js
- scripts/utils/__tests__/getPackageNames.spec.js
- scripts/utils/__tests__/parseArgs.spec.js
- scripts/utils/getPackageNames.js
- scripts/utils/parseArgs.js
- Update `parseArgs` logic
- Add unit tests for `parseArgs.js` and `generatePackageNames.js`
> Fix parseArgs to enable E2E

- packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
- packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx
- packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
See #1415
Renders the existing `id` Panel prop as an HTML `id` attribute.
> feat(core-expand-collapse): render id attribute on panels

- packages/Video/Video.jsx
- packages/Video/Video.md
- packages/Video/__tests__/Video.spec.jsx
- packages/Video/__tests__/__snapshots__/Video.spec.jsx.snap
https://telusdigital.atlassian.net/browse/RL-3649 
#1441 
Adds tracking for analytics - You can pass in a callback function to Video, in order to track analytics. The parameter this function takes will give you access to the analytics object which will be updated every time an action is fired (this inclues "play", "pause", percentage watched as an interval of "25%")
> Adding analytics to video

- packages/A11yContent/A11yContent.md
- packages/Button/Button.jsx
- packages/ButtonLink/ButtonLink.jsx
- packages/ButtonLink/ButtonLink.md
- packages/ChevronLink/ChevronLink.jsx
- packages/prop-types/PropTypes.md
- packages/prop-types/__tests__/htmlElement.spec.jsx
- packages/prop-types/htmlElement.js
- packages/prop-types/prop-types.js
Added htmlElement prop type to check for html tags as valid children for ChevronLink, ButtonLink and Button components.
> Add htmlElement prop-type for ChevronLink, ButtonLink and Button

- docs/components/overrides/StyleGuide/GlobalStyleGuide.js
- packages/Box/Box.jsx
- packages/Box/Box.md
- Adjusts prop types to make below public
- tests for below were already existing, confirmed that these worked
- added mention of below to readme to let users know that it is a valid responsive prop for box
> feat(packages): box - make below prop public

- packages/FlexGrid/FlexGrid.jsx
- packages/FlexGrid/FlexGrid.md
- packages/FlexGrid/__tests__/FlexGrid.spec.jsx
- packages/FlexGrid/__tests__/__snapshots__/FlexGrid.spec.jsx.snap
- packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap
- packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap
Added outsideGutter property to FlexGrid to enable the removal of left and right padding. This is important for layouts that require nesting of FlexGrid. With outsideGutter set to false, the child columns will align with parent FlexGrid columns as if it's under one FlexGrid.
> feat(core-flex-grid): added outsideGutter property to remove left and right padding

- packages/InteractiveIcon/Limited.jsx
- packages/InteractiveIcon/Limited.md
- packages/InteractiveIcon/svgs/Limited/CaretDown.jsx
- packages/InteractiveIcon/svgs/Limited/CaretUp.jsx
- packages/InteractiveIcon/svgs/Limited/ChevronLeft.jsx
- packages/InteractiveIcon/svgs/Limited/ChevronRight.jsx
**Description**
Adds sizing property to Limited Interactive Icons (CaretUp, CaretDown, ChevronRight, ChevronLeft). 
This change is needed for the future community component Expand Collapse Mini ([design here](https://telus.invisionapp.com/d/main#/console/13362811/428786216/preview)).
There are two size options indicating height and width in pixels, 20 and 24. 
**ScreenShots**
> feat(core-interactive-icon): add size property to limited icons

- packages/Responsive/package.json
Bug fix - this is stopping tds-community from building as it can't render <Media /> in core-responsive. 
- [] New code is unit tested
> fix(core-responsive): moving react media to dependancy

- packages/Card/Card.jsx
- packages/Card/__tests__/__snapshots__/Card.spec.jsx.snap
The original version of fullBleedImage card passes all the fullBleedImage props to the enclosing div. The styled component has been fixed to prevent this unnecessary prop pollution.
> fix(core-card): remove fullBleedImage props from div

- packages/Select/Select.jsx
- packages/Select/__tests__/__snapshots__/Select.spec.jsx.snap
See #1500 
- Hides duplicate dropdown arrow in Firefox by removing the style: `'-moz-appearance': 'textfield'`
> fix(core-select): hide firefox duplicate dropdown arrow

- packages/PriceLockup/PriceLockup.jsx
In SiteBuilder, we noticed console errors invalid prop types of `object` were being passed as props to `price`, `bottomText` and `topText` in the PriceLockup component. This is caused because the content passed is being wrapped in `WithLegal`
Example:
`topText={<WithLegal content={topText} />}`
To fix this, I'd like to add the option of adding `object` as an acceptable prop type in addition to `string` for these fields.
> fix(core-price-lockup): update proptypes

- packages/TermsAndConditions/TermsAndConditions.jsx
- packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap
See #1485
Fixes key warning by using an index since `indexedContent` and `nonIndexContent` allows components
Unfortunately having a number of issues running the environment - gitbook doesn't install.  Hoping this change is minor enough to submit?
> fix(core-terms-and-conditions): use index as key when mapping

- packages/ButtonLink/ButtonLink.jsx
- packages/ButtonLink/__tests__/__snapshots__/ButtonLink.spec.jsx.snap
This is a fix for applying hover effect for only devices that support it.
> fix(core-button-link): use media hover to apply hover color

- packages/Tooltip/TooltipButton.jsx
- packages/Tooltip/__tests__/__snapshots__/Tooltip.spec.jsx.snap
Relates to issue #1627 
prevents tooltip from submitting forms
Add `type=button` to Tooltip button to prevent it from submitting forms.
> fix(core-tooltip): add button type
