tech-snacks.md

I wanted to run this by you all for an easy way to track small tech tasks that we want to do. I've used this on other teams and found it valuable.
Tech snacks are small, short, and don't really qualify as a full user story that makes it onto the JIRA board. The word "snack" is purposeful, its not a full meal, just a snack. It should be able to be done in an hour or less, and should be doable by a single developer.
The idea is that when you find a small tech task that is outside of the scope of your current story/task, you can add it to the Tech Snacks list so that we don't lose track of it. When you find that you have a little bit of extra time (end of the day, end of the week, while waiting for a PR review, etc) you can work on one of the outstanding Tech Snacks! Don't forget to remove …

chore: Introduce a tech snacks file to track small tech tasks

---

tech-snacks.md

Made a PR to keep you all in the loop to what I added :)

chore(tech-snacks): Add a bunch of tech snacks

---

README.md

- Update link to the component catalogue and main docs
- Remove Stephen :(
- Make the badges all have the same style

docs(README.md): Update README for gitbook changes

---

packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
packages/StandaloneIcon/__tests__/__snapshots__/StandaloneIcon.spec.jsx.snap
shared/components/Clickable/Clickable.jsx
shared/components/Clickable/__tests__/__snapshots__/Clickable.spec.jsx.snap
src/components/Tooltip/__tests__/__snapshots__/Tooltip.spec.jsx.snap

- Paired with Enrico
- Added default type: button to clickable
- Updated snapshot tests

fix(clickable): Add default type

---

packages/Tooltip/__tests__/Tooltip.spec.jsx
packages/Tooltip/__tests__/__snapshots__/Tooltip.spec.jsx.snap
packages/colours/README.md
packages/css-reset/README.md
packages/css-reset/_global.scss
packages/css-reset/fonts.css
packages/css-reset/reset.css

* Small update to colours docs too
* Removed instructions for installing packages, as that belongs in getting started docs, not styleguidist docs
* Also updated a Tooltip snapshot...

docs(css-reset): Adjust docs to fix things that were not rendering properly

---

guide/getting-started/designers.md

docs(designers): add dynamic button plugin

---

renovate.json

activates [RenovateApp](https://renovateapp.com)

feat(renovate): add renovate.json

---

commitlint.config.js
guide/README.md

docs(guide): add important links to home page

---

README.md

Adding a couple folks to the team 🎉

docs(github): add Marco and Donna :wave:

---

packages/Notification/Notification.jsx
packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap

Adding this in before releasing core-notification.
- add missing FlexGrid.Row component

fix(core-notification): add flexgrid row

---

e2e/assertions/compareScreenshot.js
e2e/commands/checkAccessibility.js
e2e/commands/compareScreenshot.js
scripts/e2e.js

Adds an ability to go through each failing screenshot and update its baseline. The ability to update all screenshots automatically by using a command line argument is not featured in this PR, but will be added shortly.

Improve e2e workflow

---

guide/getting-started/designers.md

docs(designers): add the paddy plugin

---

packages/Button/Button.md

docs(button): add character range in usage

---

packages/ButtonLink/ButtonLink.md

docs(buttonlink): add character range in usage

---

packages/ChevronLink/ChevronLink.md

docs(chevronlink): add character range in usage

---

guide/design/typography.md

docs(typography): added link to brandhub

---

commitlint.config.js

This is being added to tds-community, so I'm adding it here for parity.

chore(config): add config type to commitlint

---

config/jest.config.js
config/jest/__mocks__/fileMock.js
config/jest/__mocks__/requestAnimationFrame.js
package.json
yarn.lock

...based on learnings from tds-community
🗑 yay deleting code!

chore(build): clean up jest config

---

README.md

updating active maintainers list - first commit

---

guide/contributing/developer-guide.md
guide/faq.md

- bump minimum node version to v8
- add versioning details to align with community
- make forking optional
Please squash and merge.

docs(guide): update versioning and fork guidelines to contributing doc

---

guide/contact.md

Fixing link ion contact us page

docs: fixed email link

---

renovate.json

* Add renovate retry config option so that closed Renovate pull requests retry on the following week
```
lerna info No updated packages to publish.
```

chore(github): add recreateClosed option for Renovate to retry upgrades

---

shared/styles/Typography.modules.scss

Fixed text (large) and paragraph (large), changing line-height of 2 (40px) to 32px to be compliant with DSM.
fixes #620

fix(core-paragraph): fixed text/paragraph(large) line-height

---

renovate.json

Rather than have Renovate merge commits from master, bringing PRs into an un-mergeable state; this will set Renovate to perform rebases.
There are package changes due to unpublished work on master.

chore(config): set renovate to rebase stale PRs

---

lerna.json

* Add globstars to lerna config in order to prevent certain file changes from affecting conventional commit versioning
```
No Changes
```

chore(config): add globstars to lerna ignore config

---

guide/contributing/codebase-overview.md

None
Fix a typo in codebase overview.
```
lerna info No updated packages to publish.
```

docs(guide): fix typo in codebase overview

---

packages/Notification/Notification.jsx
packages/Notification/Notification.modules.scss
packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap

See #643 
```
Changes:
- @tds/core-notification: 1.1.7 => 1.1.8 (PATCH)
```
This can be rebased.

fix(core-notification): prevent overflow of long text

---

packages/FlexGrid/Col/Col.jsx
packages/FlexGrid/Col/Col.md
packages/FlexGrid/Col/Col.modules.scss
packages/FlexGrid/Col/__tests__/Col.spec.jsx
packages/FlexGrid/Col/__tests__/__snapshots__/Col.spec.jsx.snap
packages/FlexGrid/FlexGrid.jsx
packages/FlexGrid/Row/Row.jsx
packages/FlexGrid/__tests__/__snapshots__/FlexGrid.spec.jsx.snap
packages/FlexGrid/calculateLevel.js
packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap

https://github.com/telus/tds-core/pull/708

Feature col hidden props

---

guide/SUMMARY.md
guide/accessibility/accessibility.md
guide/accessibility/responsive-content.md

None
* Add documentation to GitBook regarding page content and what we support with regards to responsive design, zoom levels, and device size
core-link is yet unpublished
```
- @tds/core-link: 1.0.2 => 1.0.3
```

docs(guide): add page for responsive content

---

packages/Heading/Heading.modules.scss
packages/css-reset/fonts.css

* Reduce character spacing for `<Heading level="h2">`
* Update font comments to more accurately reflect the font
```
Changes:
- @tds/core-css-reset: 1.1.0 => 1.1.1
- @tds/core-heading: 1.1.2 => 1.1.3
```

Reduce character spacing in heading level 2

---

.github/ISSUE_TEMPLATE/feature_template.md

added a section for designer/developer pair: to add their name and their designer or dev's name
See 
* Feature 1
* Feature 2
* Patch 1
* Patch 2

docs(feature template): added section

---

packages/ExpandCollapse/Panel/Panel.md
packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx
packages/ExpandCollapse/__tests__/ExpandCollapse.spec.jsx

Allow superscripts and HTML entities in expand collapse header via template strings.
See #762 
Closes #763

feat(core-expand-collapse): add template strings to Panel header

---

config/styleguide.config.js
e2e/tests/Components.spec.js

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

chore(core-selector-counter): remove from docs

---

packages/InputFeedback/InputFeedback.md

docs(core-input-feedback): update usage to show validation onChange

---

packages/PriceLockup/PriceLockup.jsx
packages/PriceLockup/PriceLockup.modules.scss
packages/PriceLockup/__tests__/__snapshots__/PriceLockup.spec.jsx.snap

- Fix position of dollar sign in large PriceLockups in desktop view.

fix(core-price-lockup): large lockup $ position

---

packages/ButtonGroup/ButtonGroup.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(button-group): updated usage section

---

packages/FlexGrid/Row/Row.modules.scss

fix(core-flex-grid): apply flex-shrink 0 to FlexGrid.Row

---

.github/ISSUE_TEMPLATE/defect_template.md
.github/ISSUE_TEMPLATE/feature_template.md

N/A
Add more descriptive text to issue templates.

docs(github): add more explanations to issue templates

---

circle.yml
scripts/circleci/github-pr.js

This PR adds a step that runs TDS Bot on CircleCI.

Enable TDS Bot for Circle CI

---

config/rollup.config.js

See https://telusdigital.atlassian.net/browse/TDS-1103
Remove sourcemaps

build(config): remove sourcemaps

---

circle.yml
package.json

This PR adds deploy steps to our CircleCI script. Due to the nature of this change, we need to QA on master after fully verifying we are confident in the presented changes.

chore(other): add deploy steps to circleci

---

packages/FlexGrid/Col/Col.modules.scss

See #899
yarn prepr output:
OK. 12  total assertions passed. (10.694s)
Changes:
- @tds/core-flex-grid: 2.3.3 => 2.3.4
- @tds/core-notification: 1.2.7 => 1.2.8
- @tds/core-step-tracker: 3.0.2 => 3.0.3

fix(core-flex-grid): adjust css output to be mobile-first

---

.github/PULL_REQUEST_TEMPLATE.md
docker-compose.yml
guide/contributing/codebase-overview.md
guide/getting-started/developers.md
scripts/prePr.sh

This PR cleans up some of the remaining references to Yarn in our docs.

Remove Yarn References

---

guide/SUMMARY.md

docs(guide): add tds-community link in sidenav

---

circle.yml
package-lock.json

To facilitate with automated deployments, this displays the output of `prepr` in CircleCI logs when built on `master`.

chore(other): log prepr when building on master

---

shared/components/Choice/Choice.jsx

- [x ] New code is unit tested

fix(shared-choice): made boolean a valid type for value prop

---

guide/contributing/developer-guide.md

Add documentation for developers that covers what lerna is and how to use it within TDS.

docs(guide): add table of contents and lerna tips

---

guide/contributing/developer-guide.md

- provide missing information from developer contributing docs

docs(guide): add details to lerna commands

---

guide/design/motion.md

- Added motion & animation guidelines to our documentation
- Excluded visual examples for now. This will be added once the TDS video component is released.
- (N/A) New code is unit tested 
- (N/A) For code changes, run `npm run prepr` locally

Motion & Animation docs

---

packages/Animation/README.md

Add README.md to `@tds/shared-animation`

docs(shared-animation): add README

---

circle.yml

This will rebase when TDS Bot is being used to detect version changes. PR's commits exist on the local copy of master, and this script will pull origin/master and rebase onto the local copy of master.

chore(other): add rebase on circle prepr step

---

package-lock.json
package.json

Fixes vulnerability. See https://github.com/ahmadnassri/echint/pull/100

Upgrade to echint@4.0.2

---

packages/Image/Image.jsx
packages/Image/__tests__/Image.spec.jsx
packages/Image/__tests__/__snapshots__/Image.spec.jsx.snap
packages/Image/index.cjs.js
packages/Image/index.es.js
packages/Image/package.json
packages/styles/borders.js
packages/styles/iconWrapper.js
packages/styles/index.cjs.js
packages/styles/index.es.js
packages/styles/index.js
packages/styles/links.js
packages/styles/messaging.js
packages/styles/package.json
packages/styles/position.js
packages/styles/rollup.config.js
packages/styles/spacing.js
shared/utils/safeRest.js

- Convert `@tds/core-image` to styled-components
- Add `@tds/shared-styles` package to expose 

Styled Components - @tds/core-image

---

packages/A11yContent/A11yContent.jsx
packages/A11yContent/A11yContent.modules.scss
packages/A11yContent/__tests__/A11yContent.spec.jsx
packages/A11yContent/__tests__/__snapshots__/A11yContent.spec.jsx.snap
packages/A11yContent/index.cjs.js
packages/A11yContent/index.es.js
packages/A11yContent/package.json

BREAKING CHANGE: upgrade to styled-components

feat(core-a11y-content): upgrade to styled-components

---

packages/Benefit/BenefitWithHeading/__tests__/__snapshots__/BenefitWithHeading.spec.jsx.snap
packages/Heading/Heading.jsx
packages/Heading/HeadingSup/HeadingSup.jsx
packages/Heading/HeadingSup/__tests__/HeadingSup.spec.jsx
packages/Heading/HeadingSup/__tests__/__snapshots__/HeadingSup.spec.jsx.snap
packages/Heading/__tests__/Heading.spec.jsx
packages/Heading/__tests__/__snapshots__/Heading.spec.jsx.snap
packages/Heading/index.cjs.js
packages/Heading/index.es.js
packages/Heading/package.json

- core-heading upgraded to styled components

Upgrade core-heading to Styled Components

---

guide/announcements.md

This adds the March announcements to our site. Please proofread!

docs(guide): add march announcements

---

packages/Checkbox/__tests__/__snapshots__/Checkbox.spec.jsx.snap
packages/Radio/__tests__/__snapshots__/Radio.spec.jsx.snap
shared/components/Choice/Choice.jsx
shared/components/Choice/Choice.modules.scss

[[Radio, Checkbox] Add a hover state #1000](https://github.com/telus/tds-core/issues/1000)
- Hover state effect for clickable labels of Checkboxes and Radios

 fix(core-checkbox, core-radio): add hover effect to label

---

package-lock.json
package.json

* commitizen@3.0.0 => 3.0.7
* editorconfig-checker@1.3.3 => 2.0.6 [CHANGELOG.md](https://github.com/editorconfig-checker/editorconfig-checker.javascript/blob/master/CHANGELOG.md#201---2019-02-27)
* jest-environment-enzyme@7.0.0 => 7.0.2

npm audit upgrades

---

packages/Box/Box.jsx
packages/Box/Box.md
packages/Box/__tests__/Box.spec.jsx
packages/ButtonGroup/ButtonGroup.jsx
packages/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.jsx.snap
packages/Card/Card.jsx
packages/FormField/FormField.jsx
packages/InputFeedback/InputFeedback.jsx
packages/Notification/Notification.jsx
packages/OrderedList/OrderedList.jsx
packages/PriceLockup/PriceLockup.jsx
packages/PriceLockup/__tests__/__snapshots__/PriceLockup.spec.jsx.snap
packages/Select/Select.jsx
packages/Tooltip/Bubble.jsx
packages/Tooltip/__tests__/__snapshots__/Tooltip.spec.jsx.snap
packages/UnorderedList/UnorderedList.jsx
shared/components/Choice/Choice.jsx

This removes safeRest from Box, allowing styled components to be implemented more elegantly.

feat(core-box): allow custom styles through className & style prop

---

docs/components/custom/MarkdownList/__tests__/__snapshots__/MarkdownList.spec.jsx.snap
packages/UnorderedList/UnorderedList.jsx
packages/UnorderedList/UnorderedList.md
packages/UnorderedList/__tests__/UnorderedList.spec.jsx

CHANGE: Now a list can have items with checkmarks and x

feat(core-unordered-list): added support for mixed lists

---

guide/README.md
guide/SUMMARY.md
guide/v3-upgrade.md
package-lock.json

This adds a docs page to our website that covers the upgrade path from TDS V2 to TDS V3. Please proofread and recommend ways to improve this doc!

docs(guide): add tds v3 upgrade guide

---

circle.yml
guide/announcements.md
package-lock.json
package.json

just updates to Announcements section

docs(guide): update announcements section

---

scripts/scaffolding/Component.md
scripts/scaffolding/index.cjs.js
scripts/scaffolding/index.es.js
scripts/scaffolding/package.json

- update our scaffold scripts to account for styled-components

chore(scripts): update scaffold files

---

scripts/scaffolding/package.json

chore(scripts): update scaffold package.json version

---

.gitignore
.vscode/settings.json
commitlint.config.js
guide/README.md
guide/SUMMARY.md
guide/contributing/contributing.md
guide/contributing/developer-guide.md
guide/faq.md
guide/getting-started/developers.md
guide/standards.md
scripts/commit-scope-lint.js

This adds TDS quality practices to our documentation. Still to come:
Needs review for
After merging:

Add quality checklist to contributing guide

---

guide/contributing/codebase-overview.md
guide/contributing/contributing-standards.md
guide/contributing/developer-guide.md
package-lock.json
package.json

- Add notes to developer contribution guide on documenting components
- Move tds-community contributing notes to tds-core website guide; see https://github.com/telus/tds-community/pull/242
- Contributing standards: component criteria
- Developer guide: documentation standards
- Codebase overview: React conventions
- Add markdown linting to `lint-staged`

Migrate documentation from tds-community repository

---

.github/ISSUE_TEMPLATE/defect_template.md

Make issue template better! 
After merging:

chore(github): update issue template

---

packages/UnorderedList/UnorderedItem/UnorderedItem.jsx
packages/UnorderedList/__tests__/__snapshots__/UnorderedList.spec.jsx.snap

See #924 
Addresses an issue where the icons in UnorderedList on IE 11 for Windows 7 will be misaligned with the text.

fix(core-unordered-list): fix line height values on icons for win 7

---

packages/Benefit/BenefitNoHeading/__tests__/__snapshots__/BenefitNoHeading.spec.jsx.snap
packages/Benefit/BenefitWithHeading/__tests__/__snapshots__/BenefitWithHeading.spec.jsx.snap
packages/Breadcrumbs/__tests__/__snapshots__/Breadcrumbs.spec.jsx.snap
packages/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.jsx.snap
packages/Checkbox/__tests__/__snapshots__/Checkbox.spec.jsx.snap
packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
packages/Input/__tests__/__snapshots__/Input.spec.jsx.snap
packages/PriceLockup/__tests__/__snapshots__/PriceLockup.spec.jsx.snap
packages/Radio/__tests__/__snapshots__/Radio.spec.jsx.snap
packages/Select/__tests__/__snapshots__/Select.spec.jsx.snap
packages/Spinner/__tests__/__snapshots__/Spinner.spec.jsx.snap
packages/StepTracker/__tests__/__snapshots__/StepTracker.spec.jsx.snap
packages/Text/Text.jsx
packages/Text/__tests__/Text.spec.jsx
packages/Text/__tests__/__snapshots__/Text.spec.jsx.snap
packages/Text/package.json
packages/TextArea/__tests__/__snapshots__/TextArea.spec.jsx.snap
packages/Tooltip/__tests__/__snapshots__/Tooltip.spec.jsx.snap
shared/components/ColoredTextProvider/__tests__/ColoredTextProvider.spec.jsx

**BREAKING CHANGE**: upgrade Text to styled-components

Styled Text

---

packages/Heading/Heading.jsx
packages/TermsAndConditions/Footnote/Footnote.jsx
packages/TermsAndConditions/Footnote/__tests__/__snapshots__/Footnote.spec.jsx.snap
packages/TermsAndConditions/List/List.jsx
packages/TermsAndConditions/TermsAndConditions.jsx
packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap
packages/TermsAndConditions/svg/Chevron.jsx

* Line-height of the chevron is different is affected by resets.
* Parse anchor tags in case someone adds them as HTML to legal copy
* Add tabIndex to heading and focus on `Footnote` open
* Add forwardRefs

TermsAndConditions fixes

---

guide/design/motion.md

Docs update: Link to BRC motion page

docs: docs adding link to BRC Motion page

---

packages/Checkbox/Checkbox.jsx
packages/Input/Input.jsx
packages/Input/__tests__/Input.spec.jsx
packages/Input/__tests__/__snapshots__/Input.spec.jsx.snap
packages/Radio/Radio.jsx
packages/Select/Select.jsx
packages/TextArea/TextArea.jsx

See #1158
While reviewing an issue we identified that the docs were not clear about usage of `value` vs `defaultValue`. Added better props descriptions as part of this PR.

[Input] Uncontrolled to controlled warning

---

guide/roadmap.md

update roadmap for TDS v3
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs:update-roadmap

---

packages/TermsAndConditions/Footnote/Footnote.jsx
packages/TermsAndConditions/Footnote/Footnote.md
packages/TermsAndConditions/TermsAndConditions.jsx
packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap
packages/TermsAndConditions/__tests__/renderContent.spec.jsx
packages/TermsAndConditions/package.json
packages/TermsAndConditions/renderContent.jsx

Render anchor tags as TDS Link in TermsAndConditions and Footnote components

fix(core-terms-and-conditions): render anchor tags as TDS Link

---

.github/ISSUE_TEMPLATE/icon_template.md

New icon template! 🆒
I can add an emoji to its title if you like 💎.
Hit the preview button to see the final result:

feat(github): add icon issue template

---

guide/announcements.md

(docs):docs update announcements July

---

packages/TermsAndConditions/__tests__/renderContent.spec.jsx
packages/TermsAndConditions/renderContent.jsx

Update `renderContent` to handle multiple anchor tags

fix(core-terms-and-conditions): renderContent handles multiple anchors

---

guide/design/colour.md

- Replace sass with js variables
- Remove roadmap section

docs(guide): replace sass colours with js variables

---

package-lock.json
package.json

chore(deps): remove file-loader

---

config/rollup.config.js
package.json
scripts/commit-scope-lint.js
shared/utils/__tests__/sets.spec.js

Remove core-js

---

packages/TermsAndConditions/renderContent.jsx

- FIx rendering of nodes in T&C

fix(core-terms-and-conditions): do no parse node content

---

package-lock.json
packages/Animation/FadeAndReveal.jsx
packages/Animation/Translate.jsx
packages/Animation/__tests__/__snapshots__/Translate.spec.jsx.snap
packages/Animation/package.json
packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
packages/Notification/Notification.jsx
packages/TermsAndConditions/Footnote/Footnote.jsx
packages/TermsAndConditions/Footnote/__tests__/__snapshots__/Footnote.spec.jsx.snap
packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap
packages/TermsAndConditions/svg/Chevron.jsx

- Reduce motion in TermsAndCondition 

Add reduce motion support to TermsAndCondition

---

guide/announcements.md

docs(guide): september-announcements

---

packages/TermsAndConditions/Footnote/Footnote.jsx

Focus Footnote header after entrance animation end

T&C Footnote focus after animation end

---

guide/design/motion.md

docs(guide): update link and remove repeat word

---

.all-contributorsrc
README.md
packages/Checkbox/Checkbox.jsx
packages/Checkbox/__tests__/__snapshots__/Checkbox.spec.jsx.snap
packages/Radio/Radio.jsx
packages/Radio/__tests__/__snapshots__/Radio.spec.jsx.snap

This PR addresses an issue that causes the `Radio` and `Checkbox` inputs to look disproportioned on custom browser font sizes.

Fix disproportioned Checkbox and Radio

---

guide/contributing/developer-guide.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

Update accessibility docs

---

packages/TermsAndConditions/Footnote/Footnote.md
packages/TermsAndConditions/__tests__/renderContent.spec.jsx
packages/TermsAndConditions/renderContent.jsx

This PR enables the use of <br> tags in footnote, while also improving the docs slightly.

feat(core-terms-and-conditions): add support for <br> tags in footnote

---

package-lock.json
package.json
packages/Responsive/__tests__/__snapshots__/Responsive.spec.jsx.snap
packages/Select/Select.jsx
packages/Select/Select.md
packages/Select/__tests__/Select.spec.jsx
packages/Select/__tests__/__snapshots__/Select.spec.jsx.snap

See #1276 
- Add support for select groups

feat(core-select): add support for groups

---

packages/Animation/FadeAndReveal.jsx
packages/Animation/__tests__/FadeAndReveal.spec.jsx
packages/Animation/__tests__/__snapshots__/FadeAndReveal.spec.jsx.snap
packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap

FadeAndReveal hide content

---

packages/Card/Card.jsx
packages/Card/Card.md
packages/Card/__tests__/Card.spec.jsx
packages/Card/__tests__/__snapshots__/Card.spec.jsx.snap

feat(core-card): add fullHeight property

---

guide/announcements.md

docs(guide): october announcements

---

packages/Animation/Reveal.jsx
packages/Animation/__tests__/__snapshots__/Reveal.spec.jsx.snap
packages/Notification/Notification.jsx
packages/Notification/__tests__/Notification.spec.jsx

Unmount `Notification` on dismiss

Notification unmount on dismiss

---

packages/Animation/FadeAndReveal.jsx
packages/Animation/__tests__/FadeAndReveal.spec.jsx
packages/Animation/__tests__/__snapshots__/FadeAndReveal.spec.jsx.snap
packages/Animation/package.json
packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx
packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
packages/TermsAndConditions/TermsAndConditions.jsx
packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap

Quick PR to patch the broken fade out animation on the shared FadeAndReveal component.

Fix fade animation on FadeAndReveal

---

packages/DecorativeIcon/DecorativeIcon.jsx
packages/DecorativeIcon/svgs/Bell.jsx
packages/DecorativeIcon/svgs/Download.jsx
packages/DecorativeIcon/svgs/LocationAdd.jsx
packages/DecorativeIcon/svgs/LocationRemove.jsx
packages/DecorativeIcon/svgs/LocationVerified.jsx
packages/DecorativeIcon/svgs/Phone.jsx
packages/DecorativeIcon/svgs/User.jsx
packages/Input/FeedbackIcon.jsx
packages/Input/__tests__/Input.spec.jsx
packages/Input/__tests__/__snapshots__/Input.spec.jsx.snap
packages/Input/package.json
packages/Select/__tests__/Select.spec.jsx
packages/Select/__tests__/__snapshots__/Select.spec.jsx.snap
packages/Select/package.json
packages/StandaloneIcon/StandaloneIcon.jsx
packages/TextArea/__tests__/TextArea.spec.jsx
packages/TextArea/__tests__/__snapshots__/TextArea.spec.jsx.snap
packages/TextArea/package.json

Icon excessive deprecations

---

guide/announcements.md

november announcements, have a look

docs(guide): add november announcement

---

guide/roadmap.md

docs(guide): update roadmap link

---

.all-contributorsrc
README.md
packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
packages/HairlineDivider/HairlineDivider.jsx
packages/HairlineDivider/__tests__/__snapshots__/HairlineDivider.spec.jsx.snap
packages/PriceLockup/__tests__/__snapshots__/PriceLockup.spec.jsx.snap
packages/TermsAndConditions/Footnote/__tests__/__snapshots__/Footnote.spec.jsx.snap
packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap

See: #1328 
This PR prevents the hairline divider from getting a px value of >1px when in a Flex Grid where the content wraps more than two lines.

fix(core-hairline-divider): prevent >1px width in grid with line wrap

---

.github/workflows/tds-workflow.yml

Quick PR to add the missing linting step to github actions.

test(github): add linting tests to github actions pipeline

---

package-lock.json
package.json

- use latest packages
- move `@babel/runtime` to devDependencies

chore(deps): update babel dependencies

---

packages/InteractiveIcon/Dependent.jsx
packages/InteractiveIcon/__tests__/InteractiveIcon.spec.jsx
packages/InteractiveIcon/__tests__/__snapshots__/InteractiveIcon.spec.jsx.snap
packages/Link/__tests__/Link.spec.jsx
packages/Link/__tests__/__snapshots__/Link.spec.jsx.snap

This adds jest tests related to Dependent Icon for both Link and the Interactive Icon component itself. It mainly checks for the interactions between Dependent Icon and Link.

Add Dependent Icon Related Tests

---

packages/FlexGrid/FlexGrid.jsx
packages/FlexGrid/__tests__/__snapshots__/FlexGrid.spec.jsx.snap
packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap
packages/StepTracker/__tests__/__snapshots__/StepTracker.spec.jsx.snap
packages/TermsAndConditions/Footnote/__tests__/__snapshots__/Footnote.spec.jsx.snap
packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap

See: #1355 
This fixes an issue where FlexGrids nested in a Box will not properly fill the width of the Box due to a padding override.

fix(core-flex-grid): prevent incorrect width in box

---

README.md
circle.yml

This also comments out the screenshot step in circle ci since it always fails.

chore(other): replace circle with github badge

---

guide/announcements.md

december and jan announcements

docs(guide): december and jan announcements

---

package.json

This changes the TDS package version to V3.1.0 to reflect our versioning guidelines.

chore(other): change tds package version

---

package-lock.json

Just ran `npm audit fix` and fixed 4 vulnerabilities.

chore(other): resolve vulnerabilities

---

packages/ExpandCollapse/Accordion/__tests__/__snapshots__/Accordion.spec.jsx.snap
packages/ExpandCollapse/PanelWrapper/PanelWrapper.jsx
packages/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.spec.jsx.snap
packages/TermsAndConditions/Footnote/Footnote.jsx
packages/TermsAndConditions/Footnote/__tests__/__snapshots__/Footnote.spec.jsx.snap
packages/TermsAndConditions/FootnoteLink/FootnoteLink.jsx
packages/TermsAndConditions/TermsAndConditions.jsx
packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap

fix(core-expand-collapse,core-terms-and-conditions): add button type for clickables

---

package-lock.json
package.json
packages/Box/Box.jsx
packages/Box/__tests__/Box.spec.jsx
packages/Box/__tests__/__snapshots__/Box.spec.jsx.snap

- Render `<Box between={0}>` as `display: block`

Render Box between 0 as display block

---

packages/HairlineDivider/HairlineDivider.md

**This should not be merged until https://github.com/telus/tds-core/pull/1396 is merged**
- Update `HairlineDivider` docs to include usage criteria and a realistic example of vertical HairlineDivider 

docs(core-hairline-divider): add usage, add realistic vertical divider

---

guide/announcements.md

- Add February 2020 announcements

chore(guide): add feb 2020 announcements

---

packages/Breadcrumbs/Breadcrumbs.jsx
packages/Breadcrumbs/Breadcrumbs.md
packages/Breadcrumbs/Item/Item.jsx
packages/Breadcrumbs/__tests__/Breadcrumbs.spec.jsx
packages/Breadcrumbs/__tests__/__snapshots__/Breadcrumbs.spec.jsx.snap

Fixes #1414 
- make sure visual and accessibility tests pass ⭐️ 
---
⭐️ I get the following error locally when trying to run `npm run prepr`:
```
FATAL ERROR: E2E slug not specified. Please specify the branch E2E slug (usually the branch name) using the `-n` flag.
```

feat(core-breadcrumbs): allow use of reactRouterLinkComponent on Item

---

.all-contributorsrc
.github/workflows/tds-delete-artifacts-s3.yml
.github/workflows/tds-workflow.yml
README.md
e2e/visual/index.jsx
scripts/circleci/github-pr.js

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

Push gitbook, styleguidist, and cartesians to s3

---

guide/getting-started/developers.md

Update to developer getting started page.

docs(guide): update developer getting started page

---

.github/workflows/tds-workflow.yml
e2e/visual/index.jsx
scripts/circleci/github-pr.js
scripts/e2e.js

- Change path of cartesian components in s3
- Add homepage to cartesian components
- Include docs + styleguidist in s3 push

Push docs and cartesian components to s3 on PRs

---

guide/announcements.md

- Add March 2020 announcements 
- Add April 2020 announcements

Update March and April 2020 announcements

---

.all-contributorsrc
README.md
packages/Video/Video.jsx

- this adds a patch to core-video, so that watched 100% does not get overridden by the pause event when the video completes.

Adding analytics to video

---

.github/workflows/tds-workflow.yml

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

fix(github): fix pipelines

---

.all-contributorsrc
README.md
packages/ButtonLink/package.json
packages/Checkbox/Checkbox.jsx
packages/Checkbox/__tests__/__snapshots__/Checkbox.spec.jsx.snap
packages/Radio/Radio.jsx
packages/Radio/__tests__/__snapshots__/Radio.spec.jsx.snap

Closes #1438 
Upon tabbing on configure page, Once focus reaches Checkbox (used in BIB Consent block) page does not scroll to bring Checkbox in Browser's view.
This is all happening because position of input type="checkbox" is fixed.
Making it absolute fixes the problem.
- Feature 1
- Feature 2
- Patch 1
- Patch 2

fix(core-checkbox): fixed accessibility issue

---

.all-contributorsrc
README.md
packages/Video/ControlBar/Controls/VideoProgressBar/VideoProgressBar.jsx
packages/Video/Video.jsx

- Fix video seek when more than one video is on a page
- Only call `analyticsTracking()` when the prop is provided

Fix video seek

---

circle.yml
package.json
scripts/update-contributors.js

Move update contributors step from pre-commit hook to the pipeline

Move update contributors step to pipeline

---

openshift/openshift-template.yml

chore(openshift): update cpu usage

---

openshift/openshift-template.yml

This reverts commit 2d99410f25e0b3e3df088c5f7f5c4c375ad501c9.
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

Revert "chore(openshift): update cpu usage"

---

packages/Link/Link.jsx

Ref can be either an object or a function. This PR makes sure ButtonLink takes refs that are functions.
- Feature 1
- Feature 2
- Patch 1
- Patch 2

chore(core-link): add func as a valid prop-type to forwardedRef

---

docs/components/overrides/StyleGuide/GlobalStyleGuide.js
package-lock.json
packages/FlexGrid/Col/Col.jsx
packages/FlexGrid/Col/__tests__/Col.spec.jsx
packages/FlexGrid/Col/__tests__/__snapshots__/Col.spec.jsx.snap
packages/FlexGrid/FlexGrid.jsx
packages/FlexGrid/Row/Row.jsx
packages/FlexGrid/Row/__tests__/Row.spec.jsx
packages/FlexGrid/Row/__tests__/__snapshots__/Row.spec.jsx.snap
packages/FlexGrid/__tests__/FlexGrid.spec.jsx
packages/FlexGrid/__tests__/__snapshots__/FlexGrid.spec.jsx.snap
packages/FlexGrid/index.cjs.js
packages/FlexGrid/index.es.js
packages/FlexGrid/package.json
packages/FlexGrid/rollup.config.js
packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap
packages/StepTracker/__tests__/__snapshots__/StepTracker.spec.jsx.snap
packages/TermsAndConditions/Footnote/__tests__/__snapshots__/Footnote.spec.jsx.snap
packages/TermsAndConditions/__tests__/__snapshots__/TermsAndConditions.spec.jsx.snap

Refactor `FlexGrid` to not use `react-flexbox-grid`

Refactor FlexGrid

---

packages/PriceLockup/__tests__/__snapshots__/PriceLockup.spec.jsx.snap
packages/TermsAndConditions/FootnoteLink/FootnoteLink.jsx

Make footnote link cursor pointer

---

config/styleguide.config.js
packages/Paragraph/index.es.js
packages/TermsAndConditions/Disclaimer/Disclaimer.jsx
packages/TermsAndConditions/Disclaimer/Disclaimer.md
packages/TermsAndConditions/Disclaimer/__tests__/Disclaimer.spec.jsx
packages/TermsAndConditions/Disclaimer/__tests__/__snapshots__/Disclaimer.spec.jsx.snap
packages/TermsAndConditions/index.js
packages/TermsAndConditions/package.json

Add Disclaimer component

---

packages/ButtonGroup/ButtonGroupItem/ButtonGroupItem.jsx
packages/ButtonGroup/__tests__/__snapshots__/ButtonGroup.spec.jsx.snap

fix(core-button-group): move focus to button group when navigated to

---

packages/Small/Small.md
packages/Strong/Strong.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

Update Small and Strong usage

---

config/styleguide.config.js
e2e/visual/components/CartesianTextButton.jsx
packages/TextButton/README.md
packages/TextButton/TextButton.jsx
packages/TextButton/TextButton.md
packages/TextButton/__tests__/TextButton.spec.jsx
packages/TextButton/__tests__/__snapshots__/TextButton.spec.jsx.snap
packages/TextButton/index.cjs.js
packages/TextButton/index.es.js
packages/TextButton/package-lock.json
packages/TextButton/package.json
packages/TextButton/rollup.config.js

Per [DJR-3057](https://telusdigital.atlassian.net/browse/DJR-3057)
- Creates the TextButton component, a component that looks like a link but functions like a button
- [X ] New code is unit tested

DJR-3057 Text button

---

packages/ButtonLink/ButtonLink.jsx
packages/ButtonLink/__tests__/__snapshots__/ButtonLink.spec.jsx.snap

Update ButtonLink component to set visited, hover and link behavior

Update ButtonLink component to set visited, hover and link behavior

---

.colophon.yml
README.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

chore(other): update colophon and team members

---

e2e/visual/components/CartesianPriceLockup.jsx
packages/PriceLockup/PriceLockup.jsx
packages/PriceLockup/PriceLockup.md
packages/PriceLockup/__tests__/__snapshots__/PriceLockup.spec.jsx.snap

- format a11yText with commas for screenreader to pause appropriately 
- hide rate text from screen reader and replace with a11yContent

Update price lockup for screenreader

---

config/nightwatch.saucelabs.conf.js

- Update saucelabs to test with firefox 80

chore(e2e): upgrade saucelabs to use firefox 80

---

packages/DecorativeIcon/SVGIcon.jsx
packages/FeedbackIcon/FeedbackIcon.jsx
packages/FeedbackIcon/__tests__/FeedbackIcon.spec.jsx
packages/FeedbackIcon/__tests__/__snapshots__/FeedbackIcon.spec.jsx.snap
packages/FlexGrid/FlexGrid.jsx
packages/Input/__tests__/__snapshots__/Input.spec.jsx.snap
packages/InteractiveIcon/Dependent.jsx
packages/InteractiveIcon/Limited.jsx
packages/InteractiveIcon/__tests__/__snapshots__/InteractiveIcon.spec.jsx.snap
packages/Link/__tests__/__snapshots__/Link.spec.jsx.snap
packages/Notification/__tests__/__snapshots__/Notification.spec.jsx.snap
packages/Select/__tests__/__snapshots__/Select.spec.jsx.snap
packages/TextArea/__tests__/__snapshots__/TextArea.spec.jsx.snap
packages/helpers/index.js
packages/helpers/pixelToRem.js
shared/components/Icon/Icon.jsx

- Allow icon size scaling with browser font size

Icon size scaling with browser font size

---

packages/Notification/Notification.jsx

adding event listener so height is adjusted properly
Fixes issue where content overflows the container when the browser is resized. See example below:

fix(core-notification): fix component resizing

---

guide/README.md

- Updating the landing page notification message with a positive message of upcoming changes
- Text change only

Updating notification message

---

packages/DecorativeIcon/SVGIcon.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-decorative-icon): fix SVG icon docs

---

guide/getting-started/designers.md

See [#1628](https://github.com/telus/tds-core/issues/1628)
- Update designers.md guide

chore(guide): add figma docs to tds

---

guide/getting-started/designers.md

Reverts telus/tds-core#1688
The CI is failing since this PR.
I revert it, because I've other urgent issues to fix.
Then, I'll come back to this one...

Revert "chore(guide): add figma docs to tds"

---

package.json

See 
- Fix ci issue with figma files

chore(other): ignore figma files

---

README.md

Add Bill Somen as main maintener of TDS-CORE

chore(other): add bill somen as dev to readme

---

guide/getting-started/designers.md

See #1686 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

chore(guide): update designer guide with figma info

---

guide/getting-started/designers.md

fix(guide): fix typo in designers.md file

---

packages/FeedbackIcon/FeedbackIcon.jsx

See #1702 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

chore(packages): fixing alternative text on feedback icon

---

packages/Breadcrumbs/Breadcrumbs.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-breadcrumbs): update-tds-telus-breadcrumbs-documentation

---

.github/workflows/tds-workflow.yml
package.json

Attempt to fix Github Actions (`lerna publish` issue)

fix: lerna publish from-package to recover github actions

---

packages/Box/Box.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-box): update-tds-telus-box-documentation

---

packages/Button/Button.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-button): update-tds-telus-button-documentation

---

packages/Image/Image.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-image): update-tds-telus-image-documentation

---

packages/Link/Link.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-link): update-tds-telus-link-documentation

---

packages/ChevronLink/ChevronLink.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-chevron-link): update-tds-telus-chevron-link-documentation

---

packages/TextButton/TextButton.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-text-button): update-tds-telus-text-button-documentation

---

packages/InteractiveIcon/IconButton.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-interactive-icon): update-tds-telus-icon-button-documentation

---

packages/Radio/Radio.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-radio): update-tds-telus-radio-documentation

---

packages/TextArea/TextArea.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-text-area): update-tds-telus-text-area-documentation)

---

packages/Checkbox/Checkbox.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-checkbox): update-tds-telus-checkbox-documentation

---

packages/WebVideo/WebVideo.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-web-video): update-tds-telus-web-video-documentation

---

packages/Video/Video.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-video): update-tds-telus-video-documentation

---

packages/TermsAndConditions/TermsAndConditions.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-terms-and-conditions): update-tds-terms-and-conditions-docs

---

packages/ResponsiveImage/ResponsiveImage.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-responsive-image): update-tds-telus-responsive-image-docs

---

packages/PriceLockup/PriceLockup.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-price-lockup): update-tds-telus-price-lockup-documentation

---

packages/OrderedList/OrderedList.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-ordered-list): update-tds-telus-ordered-list-documentation

---

packages/TermsAndConditions/Footnote/Footnote.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-terms-and-conditions): update-tds-telus-footnote-documentation

---

packages/ExpandCollapse/ExpandCollapse.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-expand-collapse): update-tds-telus-expand-collapse-docs

---

packages/Card/Card.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-card): update-tds-telus-card-documentation

---

packages/colours/Colours.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-colours): update-tds-telus-colour-documentation

---

docs/Typography.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(docs): update-tds-telus-typography-documentation

---

docs/icons.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(docs): update-tds-telus-icons-documentation

---

packages/Video/Video.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-video): fix-typo-tds-telus-video-documentation

---

docs/Typography.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(docs): fix-typo-tds-telus-typography-documentation

---

packages/Tooltip/Tooltip.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(core-tooltip): fix-typo-tds-telus-tooltip-documentation

---

guide/README.md

See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

docs(guide): fix allium url in tds homepage

---

guide/design/principles.md

Correct link
- [Accessibility](https://www.telus.com/en/brand-resources/standards/accessibility-in-technology)
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

Updated Accessibility Link

---

guide/design/principles.md

See #1781 
- Feature 1
- Feature 2
- Patch 1
- Patch 2

chore(guide): update guide links

---

packages/PriceLockup/__tests__/__snapshots__/PriceLockup.spec.jsx.snap
packages/TermsAndConditions/FootnoteLink/FootnoteLink.jsx

See #1526  
- Added data-nosnippet attribute to the FootnoteLink
- Added doc-noteref role to Ay11Content
- 
- ## Checklist before submitting pull request

1526 seo enhancement to footnote annotations
